""" PROBLEM COMPLETED BY JEFF BAYES
Project Euler Problem #2 - Even Fibonacci numbers.
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, and 89.
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. """

def fibonacci_sum_evens(number_cap):
    x, y = 0, 1     # Base terms in the Fibonacci sequence.
    fibo_sum = 0
    while y <= number_cap:
        if y % 2 == 0:
            fibo_sum += y
        print n_sum
    if x < 4000000:
        fibonacci_sum(y, z, n_sum)
        
fibonacci_sum(0, 1, 0)

